# Form implementation generated from reading ui file 'GSIS.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SSIS(object):
    def setupUi(self, SSIS):
        SSIS.setObjectName("SSIS")
        SSIS.resize(801, 600)
        SSIS.setMinimumSize(QtCore.QSize(801, 600))
        SSIS.setMaximumSize(QtCore.QSize(801, 600))
        SSIS.setMouseTracking(False)
        SSIS.setStyleSheet("background-color:rgb(34, 40, 49)")
        SSIS.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=SSIS)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 781, 581))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tabWidget.setFont(font)
        self.tabWidget.setStatusTip("")
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color:rgb(34, 40, 49)")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.memberTab = QtWidgets.QWidget()
        self.memberTab.setObjectName("memberTab")
        self.studentTable = QtWidgets.QTableView(parent=self.memberTab)
        self.studentTable.setGeometry(QtCore.QRect(20, 100, 741, 431))
        self.studentTable.setAutoFillBackground(False)
        self.studentTable.setStyleSheet("background-color: rgb(238, 238, 238)")
        self.studentTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.studentTable.setObjectName("studentTable")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.memberTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 741, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchpushButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.searchpushButton.setStyleSheet("background-color:rgb(0, 173, 181);\n"
"font: 87 8pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.searchpushButton.setObjectName("searchpushButton")
        self.horizontalLayout.addWidget(self.searchpushButton)
        self.studentLineEdit = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.studentLineEdit.setStyleSheet("background-color: rgb(238, 238, 238)")
        self.studentLineEdit.setMaxLength(250)
        self.studentLineEdit.setObjectName("studentLineEdit")
        self.horizontalLayout.addWidget(self.studentLineEdit)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.memberTab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 0, 741, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addButtonStudent = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.addButtonStudent.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.addButtonStudent.setMouseTracking(False)
        self.addButtonStudent.setStyleSheet("background-color:rgb(0, 173, 181);\n"
"font: 87 8pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.addButtonStudent.setObjectName("addButtonStudent")
        self.horizontalLayout_3.addWidget(self.addButtonStudent)
        self.addButtonStudent_2 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.addButtonStudent_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.addButtonStudent_2.setMouseTracking(False)
        self.addButtonStudent_2.setStyleSheet("background-color:rgb(0, 173, 181);\n"
"font: 87 8pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.addButtonStudent_2.setObjectName("addButtonStudent_2")
        self.horizontalLayout_3.addWidget(self.addButtonStudent_2)
        self.deleteButtonStudent = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.deleteButtonStudent.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.deleteButtonStudent.setStyleSheet("background-color:rgb(0, 173, 181);\n"
"font: 87 8pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.deleteButtonStudent.setObjectName("deleteButtonStudent")
        self.horizontalLayout_3.addWidget(self.deleteButtonStudent)
        self.tabWidget.addTab(self.memberTab, "")
        self.courseTab = QtWidgets.QWidget()
        self.courseTab.setObjectName("courseTab")
        self.courseTable = QtWidgets.QTableView(parent=self.courseTab)
        self.courseTable.setGeometry(QtCore.QRect(20, 100, 741, 431))
        self.courseTable.setAutoFillBackground(False)
        self.courseTable.setStyleSheet("background-color: rgb(238, 238, 238)")
        self.courseTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.courseTable.setObjectName("courseTable")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.courseTab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 50, 741, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchpushButton_2 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.searchpushButton_2.setStyleSheet("background-color:rgb(0, 173, 181);\n"
"font: 87 8pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.searchpushButton_2.setObjectName("searchpushButton_2")
        self.horizontalLayout_2.addWidget(self.searchpushButton_2)
        self.studentLineEdit_2 = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_2)
        self.studentLineEdit_2.setStyleSheet("background-color: rgb(238, 238, 238)")
        self.studentLineEdit_2.setMaxLength(500)
        self.studentLineEdit_2.setObjectName("studentLineEdit_2")
        self.horizontalLayout_2.addWidget(self.studentLineEdit_2)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=self.courseTab)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 0, 741, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addButtonCourse = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.addButtonCourse.setStyleSheet("background-color:rgb(0, 173, 181);\n"
"font: 87 8pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.addButtonCourse.setObjectName("addButtonCourse")
        self.horizontalLayout_4.addWidget(self.addButtonCourse)
        self.addButtonStudent_3 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.addButtonStudent_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.addButtonStudent_3.setMouseTracking(False)
        self.addButtonStudent_3.setStyleSheet("background-color:rgb(0, 173, 181);\n"
"font: 87 8pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.addButtonStudent_3.setObjectName("addButtonStudent_3")
        self.horizontalLayout_4.addWidget(self.addButtonStudent_3)
        self.deleteButtonCourse = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.deleteButtonCourse.setStyleSheet("background-color:rgb(0, 173, 181);\n"
"font: 87 8pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.deleteButtonCourse.setObjectName("deleteButtonCourse")
        self.horizontalLayout_4.addWidget(self.deleteButtonCourse)
        self.tabWidget.addTab(self.courseTab, "")
        SSIS.setCentralWidget(self.centralwidget)

        self.retranslateUi(SSIS)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SSIS)

    def retranslateUi(self, SSIS):
        _translate = QtCore.QCoreApplication.translate
        SSIS.setWindowTitle(_translate("SSIS", "MainWindow"))
        self.searchpushButton.setText(_translate("SSIS", "Search"))
        self.studentLineEdit.setText(_translate("SSIS", "Input Member\'s ID for Searching"))
        self.studentLineEdit.setPlaceholderText(_translate("SSIS", "Input Student ID For Searching"))
        self.addButtonStudent.setText(_translate("SSIS", "ADD GYM MEMBER"))
        self.addButtonStudent_2.setText(_translate("SSIS", "EDIT INFORMATION"))
        self.deleteButtonStudent.setText(_translate("SSIS", "DELETE INFORMATION"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.memberTab), _translate("SSIS", "MEMBER"))
        self.searchpushButton_2.setText(_translate("SSIS", "Search"))
        self.studentLineEdit_2.setText(_translate("SSIS", "Input Trainer\'s ID for Searching"))
        self.studentLineEdit_2.setPlaceholderText(_translate("SSIS", "Input Student ID For Searching"))
        self.addButtonCourse.setText(_translate("SSIS", "ADD TRAINER"))
        self.addButtonStudent_3.setText(_translate("SSIS", "EDIT INFORMATION"))
        self.deleteButtonCourse.setText(_translate("SSIS", "DELETE INFORMATION"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.courseTab), _translate("SSIS", "TRAINER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SSIS = QtWidgets.QMainWindow()
    ui = Ui_SSIS()
    ui.setupUi(SSIS)
    SSIS.show()
    sys.exit(app.exec())
